### ISSUE TITLE
In step 4 of test process ,fuction of line was not declared in this scope, it may attributed of loading my opencv lib,shoud l change some headfiles in MakeFiles? thank you very much!

### ISSUE THREAD

**Issue by XieZixiUSTC** [cardwing/Codes-for-Lane-Detection#193]
xiezixi@lthpc:~/Codes-for-Lane-Detection-master/ENet-Label-Torch/tools/lane_evaluation$ make
CXX src/evaluate.cpp
src/evaluate.cpp: In function \u2018void visualize(std::__cxx11::string&, std::vector<std::vector<cv::Point_<float> > >&, std::vector<std::vector<cv::Point_<float> > >&, std::vector<int>, int)\u2019:
src/evaluate.cpp:271:59: error: \u2018line\u2019 was not declared in this scope
    line(img, p_interp[n], p_interp[n+1], color, width_lane);
                                                           ^
Makefile:36: recipe for target 'build/src/evaluate.o' failed
make: *** [build/src/evaluate.o] Error 1
xiezixi@lthpc:~/Codes-for-Lane-Detection-master/ENet-Label-Torch/tools/lane_evaluation$

**Comment by cardwing** [comment]
Line() is a function of opencv. It seems that your opencv is not properly installed. Please check it. Besides, what is the version of your opencv? The current codes work well in opencv 2.4.x (>= 2.4.8).

**Comment by BoSeal** [comment]
@XieZixiUSTC,你好，在make后，我出现和你相同的问题，请问你是怎么解决的？我使用的是OpenCV3.4.1版本

**Comment by XieZixiUSTC** [comment]
@cardwing @BoSeal  my opencv version is 3.4.6, i solved this issue by add some libs in Makefile, as follows:LIBRARIES += opencv_core opencv_highgui opencv_imgproc  opencv_imgcodecs;INCLUDE := -I /usr/local/include/.Also add (#include <opencv2/opencv.hpp>) in ./src/evaluate.cpp and lane_compare.cpp. this method worked for me , i hope this comment can help you!

**Comment by BoSeal** [comment]
@XieZixiUSTC ，我按照你的解决方案，但是还是不行，出现了以下新问题：
(base) dcase@dcase-PowerEdge-R730:~/fhb/Codes-for-Lane-Detection-master/SCNN-Tensorflow/lane-detection-model/Pan-SCNN-master/SCNN-master/tools/lane_evaluation$ make
CXX/LD evaluate
/usr/bin/ld: build/src/lane_compare.o: undefined reference to symbol '_ZN2cv4lineERKNS_17_InputOutputArrayENS_6Point_IiEES4_RKNS_7Scalar_IdEEiii'
//usr/local/lib/libopencv_imgproc.so.3.4: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:53: recipe for target 'evaluate' failed
make: *** [evaluate] Error 1

**Comment by BoSeal** [comment]
@XieZixiUSTC @cardwing ,请问使用opencv评估性能时，需要激活配置的tensorflow-gpu的conda环境么？作为新手，对这些不清楚，望能解答

**Comment by cardwing** [comment]
不需要激活其他环境。测试代码在opencv 2.4.x (>= 2.4.8) 上可以跑通，所以建议你重新安装一下opencv。
